import ListRepositories from "../../components/Repository/ListRepositories";
import { IRepository } from "../../interfaces/IRepository"

function index({ result }: IRepository[] | any) {
    const repos = [
        {
            "id": 455904977,
            "node_id": "R_kgDOGyyO0Q",
            "name": "agenda_bot",
            "full_name": "SimonDuperray/agenda_bot",
            "private": false,
            "owner": {
                "login": "SimonDuperray",
                "id": 64204457,
                "node_id": "MDQ6VXNlcjY0MjA0NDU3",
                "avatar_url": "https://avatars.githubusercontent.com/u/64204457?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/SimonDuperray",
                "html_url": "https://github.com/SimonDuperray",
                "followers_url": "https://api.github.com/users/SimonDuperray/followers",
                "following_url": "https://api.github.com/users/SimonDuperray/following{/other_user}",
                "gists_url": "https://api.github.com/users/SimonDuperray/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/SimonDuperray/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/SimonDuperray/subscriptions",
                "organizations_url": "https://api.github.com/users/SimonDuperray/orgs",
                "repos_url": "https://api.github.com/users/SimonDuperray/repos",
                "events_url": "https://api.github.com/users/SimonDuperray/events{/privacy}",
                "received_events_url": "https://api.github.com/users/SimonDuperray/received_events",
                "type": "User",
                "site_admin": false
            },
            "html_url": "https://github.com/SimonDuperray/agenda_bot",
            "description": null,
            "fork": false,
            "url": "https://api.github.com/repos/SimonDuperray/agenda_bot",
            "forks_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/forks",
            "keys_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/teams",
            "hooks_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/hooks",
            "issue_events_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/issues/events{/number}",
            "events_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/events",
            "assignees_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/assignees{/user}",
            "branches_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/branches{/branch}",
            "tags_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/tags",
            "blobs_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/languages",
            "stargazers_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/stargazers",
            "contributors_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/contributors",
            "subscribers_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/subscribers",
            "subscription_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/subscription",
            "commits_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/contents/{+path}",
            "compare_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/merges",
            "archive_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/downloads",
            "issues_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/issues{/number}",
            "pulls_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/labels{/name}",
            "releases_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/releases{/id}",
            "deployments_url": "https://api.github.com/repos/SimonDuperray/agenda_bot/deployments",
            "created_at": "2022-02-05T15:20:35Z",
            "updated_at": "2022-02-11T11:29:50Z",
            "pushed_at": "2022-02-12T11:25:36Z",
            "git_url": "git://github.com/SimonDuperray/agenda_bot.git",
            "ssh_url": "git@github.com:SimonDuperray/agenda_bot.git",
            "clone_url": "https://github.com/SimonDuperray/agenda_bot.git",
            "svn_url": "https://github.com/SimonDuperray/agenda_bot",
            "homepage": null,
            "size": 25,
            "stargazers_count": 1,
            "watchers_count": 1,
            "language": "Python",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "forks_count": 0,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 0,
            "license": null,
            "allow_forking": true,
            "is_template": false,
            "topics": [],
            "visibility": "public",
            "forks": 0,
            "open_issues": 0,
            "watchers": 1,
            "default_branch": "master"
        },
        {
            "id": 389537122,
            "node_id": "MDEwOlJlcG9zaXRvcnkzODk1MzcxMjI=",
            "name": "ai_ANN_Regression",
            "full_name": "SimonDuperray/ai_ANN_Regression",
            "private": false,
            "owner": {
                "login": "SimonDuperray",
                "id": 64204457,
                "node_id": "MDQ6VXNlcjY0MjA0NDU3",
                "avatar_url": "https://avatars.githubusercontent.com/u/64204457?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/SimonDuperray",
                "html_url": "https://github.com/SimonDuperray",
                "followers_url": "https://api.github.com/users/SimonDuperray/followers",
                "following_url": "https://api.github.com/users/SimonDuperray/following{/other_user}",
                "gists_url": "https://api.github.com/users/SimonDuperray/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/SimonDuperray/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/SimonDuperray/subscriptions",
                "organizations_url": "https://api.github.com/users/SimonDuperray/orgs",
                "repos_url": "https://api.github.com/users/SimonDuperray/repos",
                "events_url": "https://api.github.com/users/SimonDuperray/events{/privacy}",
                "received_events_url": "https://api.github.com/users/SimonDuperray/received_events",
                "type": "User",
                "site_admin": false
            },
            "html_url": "https://github.com/SimonDuperray/ai_ANN_Regression",
            "description": null,
            "fork": false,
            "url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression",
            "forks_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/forks",
            "keys_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/teams",
            "hooks_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/hooks",
            "issue_events_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/issues/events{/number}",
            "events_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/events",
            "assignees_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/assignees{/user}",
            "branches_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/branches{/branch}",
            "tags_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/tags",
            "blobs_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/languages",
            "stargazers_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/stargazers",
            "contributors_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/contributors",
            "subscribers_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/subscribers",
            "subscription_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/subscription",
            "commits_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/contents/{+path}",
            "compare_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/merges",
            "archive_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/downloads",
            "issues_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/issues{/number}",
            "pulls_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/labels{/name}",
            "releases_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/releases{/id}",
            "deployments_url": "https://api.github.com/repos/SimonDuperray/ai_ANN_Regression/deployments",
            "created_at": "2021-07-26T06:52:59Z",
            "updated_at": "2021-07-26T06:54:50Z",
            "pushed_at": "2021-07-26T06:54:48Z",
            "git_url": "git://github.com/SimonDuperray/ai_ANN_Regression.git",
            "ssh_url": "git@github.com:SimonDuperray/ai_ANN_Regression.git",
            "clone_url": "https://github.com/SimonDuperray/ai_ANN_Regression.git",
            "svn_url": "https://github.com/SimonDuperray/ai_ANN_Regression",
            "homepage": null,
            "size": 2328,
            "stargazers_count": 0,
            "watchers_count": 0,
            "language": "Jupyter Notebook",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "forks_count": 0,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 0,
            "license": null,
            "allow_forking": true,
            "is_template": false,
            "topics": [],
            "visibility": "public",
            "forks": 0,
            "open_issues": 0,
            "watchers": 0,
            "default_branch": "master"
        }
    ]
    return (
        <div>
            <h1>repos page</h1>
            <ListRepositories repositories={repos} />
        </div>
    )
}

// export async function getServerSideProps() {
//     const res = await fetch("https://api.github.com/users/SimonDuperray/repos");
//     const repos = await res.json();
//
//     const interfacedRepositories: IRepository[] = [];
//     for(let i=0; i<repos.length; i++) {
//         let bufferRepo: IRepository = {
//             id: repos[i].id,
//             name: repos[i].name,
//             language: repos[i].language,
//             createdAt: repos[i].created_at,
//             pushedAt: repos[i].pushed_at
//         }
//         interfacedRepositories.push(bufferRepo);
//     }
//     return {
//         props: {
//             result: interfacedRepositories
//         }
//     }
// }

export default index;